<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <!-- Site favicon -->
        <link rel='shortcut icon' type='image/x-icon' href='images/favicon.ico' />
        <!-- /site favicon -->

        <!-- Entypo font stylesheet -->
        <link href="css/entypo.css" rel="stylesheet">
        <!-- /entypo font stylesheet -->

        <!-- Font awesome stylesheet -->
        <link href="css/font-awesome.min.css" rel="stylesheet">
        <!-- /font awesome stylesheet -->

        <!-- Bootstrap stylesheet min version -->
        <link href="css/bootstrap.min.css" rel="stylesheet">
        <!-- /bootstrap stylesheet min version -->

        <!-- Mouldifi core stylesheet -->
        <link href="css/mouldifi-core.css" rel="stylesheet">
        <!-- /mouldifi core stylesheet -->

        <link href="css/mouldifi-forms.css" rel="stylesheet">

        <!-- /fonts   -->
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">

        <link rel="stylesheet" media="screen" href="css/main.css">
        <link rel="stylesheet" media="screen" href="css/app_1.min.css">
        <link rel="stylesheet" media="screen" href="css/app_2.min.css">
        <script data-main="app/req-main" src="js/require.js"></script> 
    </head>
    <body>
        <nav class="navbar navbar-inverse">
            <div>
                <nav class="navbar navbar-default">
                  <div class="container-fluid">
                    <div class="navbar-header">
                      <a class="navbar-brand" href="/">Home</a>
                    </div>
                    <div class="navbar-header">
                      <a class="navbar-brand" href="/#wall">Add post</a>
                    </div>
                    <div class="navbar-header navbar-right">
                      <button id="logout"type='button' class='btn btn-primary'>Log out</button>
                    </div> 
                  </div><!-- /.container-fluid -->
                </nav>
            </div>
        </nav>
       <section id="content" class="main-content">
            <div class="container">
                <div class="block-header">
                </div>
            </div>
        </section>
    
    </body>
</html>
